version: 1.0.{build}
os: Visual Studio 2015
environment:
  DNX_FEED: https://www.nuget.org/api/v2
install:
- cmd: set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH% dnvm install 1.0.0-rc1-update1
build:
  verbosity: detailed
artifacts:
- path: artifacts/packages/*.nupkg